# Generated by Django 3.2.5 on 2021-07-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210709_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='transitioning',
            field=models.BooleanField(default=False),
        ),
    ]
